#!/usr/bin/env bash

set -euo pipefail

if [ ! "$#" -eq 1 ]; then
	echo "Usage:"
	echo "  $0 <action> <distribname>"
	echo ""
	echo "action      : build|run"
	echo "distribname : Choose from below list :"
	echo ""

	ls docker/**.Dockerfile | sed 's/\.Dockerfile//' | sed 's/docker\///'
fi

# Run docker image
if [ "$#" -eq 1 ]; then
	docker run -it --rm \
		-w /root/.config/nvim \
		-v "$PWD":/root/.config/nvim \
		-v /tmp/local-vide-"$1":/root/.local \
		vide-"$1" 
	exit 0
fi
