#!/usr/bin/env bash

set -euo pipefail

NVIMVERSION=0.9.1
PYTHONVERSION=3.11
DISTRIBNAME=ubuntu

# Build docker image
if [ "$#" -eq 1 ]; then
  if [ "$1" == "docker-build" ]; then
    docker build -t vide-$DISTRIBNAME -f docker/$DISTRIBNAME.Dockerfile .
    exit 0
  fi

# Run docker container with DISTRIBNAME image
  if [ "$1" == "docker-run" ]; then
    docker run -it --rm \
      -w /root/.config/nvim \
      -v $PWD:/root/.config/nvim \
      -v /tmp/local-vide-$DISTRIBNAME:/root/.local \
      vide-$DISTRIBNAME
    exit 0
  fi
fi

# Check if installation run as root
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root"
  exit 1
fi

# System requirements
apt-get update
apt-get install --no-install-recommends -y ca-certificates build-essential \
  cmake cargo git curl wget unzip npm yarn xclip

# Required by Lazyvim
apt-get install --no-install-recommends -y fzf fd-find ripgrep tree-sitter-cli
ln -s $(which fdfind) /usr/local/bin/fd

# lazygit
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar -C /usr/local/bin -xf /tmp/lazygit.tar.gz lazygit

# python
apt-get install -y python3
update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHONVERSION} 1

# Install Neovim
curl -Lo /tmp/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/v${NVIMVERSION}/nvim-linux64.tar.gz
tar xzf /tmp/nvim-linux64.tar.gz --exclude man -C /usr/local/ --strip-components=1

# Install rustup (for building some neovim plugins)
curl -o /tmp/rustup.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs && chmod +x /tmp/rustup.sh && /tmp/rustup.sh -y
rm -f /tmp/rustup.sh

# Build rust plugins
cargo install selene shellharden

# Install requirements neede by neovim plugins
apt-get install -y lua-check shellcheck
